project 'CandyPlayerDemo.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
inhibit_all_warnings!

target 'CandyPlayerDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CandyPlayerDemo
  pod 'CandyPlayer'  , :path => '../'
end
