project 'CandyPlayerDemo.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CandyPlayerDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CandyPlayerDemo
#   pod 'ReactiveObjC' , '~>3.0.0'
  pod 'CandyPlayer'  , :path => '../'
end
